AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        firstName:
            type: string
            length: '50'
        email:
            type: string
            length: '255'
        createdAt:
            type: datetime
        phone:
            type: string
            length: '10'
        updateAt:
            type: datetime
    lifecycleCallbacks: {  }
